#!/usr/bin/env python3
"""
Rebuild sitemap.xml from index.html.

Why this exists: every gallery on the page is injected by JavaScript from a
`data-seq` / `data-list` / `data-shots` attribute. Google does render JS, but
image discovery through rendering is the least reliable path it has — and this
is a photographer's site, where image search is a real traffic channel. An
image sitemap tells Google the files exist without depending on rendering at all.

Run it after changing any gallery attribute:

    python3 tools/build-sitemap.py

Google dropped support for <image:caption>, <image:title>, <image:geo_location>
and <image:license> in May 2022, so each entry is just an <image:loc>. The URLs
point at the JPEG/PNG rather than the WebP twin: that is the <img src> the
markup actually declares, and it is fetchable by anything.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "index.html"
OUT = ROOT / "sitemap.xml"
SITE = "https://chenkessler.com/"
IMG = "assets/v3/img/"
LASTMOD = "2026-08-16"


def pad(n: int) -> str:
    return f"{n:02d}"


def collect() -> list[str]:
    html = PAGE.read_text(encoding="utf-8")
    # The script block documents these same attributes in its comments, and those
    # examples parse just as well as the real thing — scan the markup only.
    html = html.split("<body>", 1)[-1].split("<script>", 1)[0]
    found: list[str] = []

    def add(rel: str) -> None:
        if rel not in found:
            found.append(rel)

    # static <img src="assets/…"> and the <source srcset> twins' originals
    for m in re.finditer(r'<img[^>]+src="(assets/[^"]+\.(?:jpg|jpeg|png))"', html):
        add(m.group(1))

    # data-seq="folder/prefix|1-8"
    for m in re.finditer(r'data-seq="([^|"]+)\|(\d+)-(\d+)"', html):
        folder, lo, hi = m.group(1), int(m.group(2)), int(m.group(3))
        base = folder.split("/")
        for i in range(lo, hi + 1):
            add(f"{IMG}{base[0]}/{base[1]}-{pad(i)}.jpg")

    # data-list="folder/prefix|1,4,9"
    for m in re.finditer(r'data-list="([^|"]+)\|([^"]+)"', html):
        base = m.group(1).split("/")
        for n in m.group(2).split(","):
            add(f"{IMG}{base[0]}/{base[1]}-{pad(int(n))}.jpg")

    # data-shots="folder/prefix|1:0.667,4:1.5"
    for m in re.finditer(r'data-shots="([^|"]+)\|([^"]+)"', html):
        base = m.group(1).split("/")
        for n in re.findall(r'(\d+):', m.group(2)):
            add(f"{IMG}{base[0]}/{base[1]}-{pad(int(n))}.jpg")

    missing = [r for r in found if not (ROOT / r).exists()]
    if missing:
        print("WARNING — referenced but not on disk:", file=sys.stderr)
        for r in missing:
            print("  " + r, file=sys.stderr)
        found = [r for r in found if r not in missing]

    return found


def build(images: list[str]) -> str:
    blocks = "\n".join(
        f"    <image:image><image:loc>{SITE}{r}</image:loc></image:image>"
        for r in images
    )
    alts = (
        f'    <xhtml:link rel="alternate" hreflang="en" href="{SITE}" />\n'
        f'    <xhtml:link rel="alternate" hreflang="he" href="{SITE}?lang=he" />\n'
        f'    <xhtml:link rel="alternate" hreflang="x-default" href="{SITE}" />'
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/build-sitemap.py — do not hand-edit, rerun the script. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

  <url>
    <loc>{SITE}</loc>
    <lastmod>{LASTMOD}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>1.0</priority>
{alts}
{blocks}
  </url>

  <url>
    <loc>{SITE}?lang=he</loc>
    <lastmod>{LASTMOD}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.9</priority>
{alts}
{blocks}
  </url>

</urlset>
"""


def main() -> None:
    images = collect()
    if not images:
        sys.exit("no images found — did index.html change shape?")
    OUT.write_text(build(images), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(images)} images across 2 URLs")


if __name__ == "__main__":
    main()
